
// user.id.update(25)
// user.id.typeOf()
// user.id.valueOf()
// user.id.lengthOf()
// user.id.toString()
// user.id.toJSON()
// user.id.on('update', function() {})
// user.id.on('empty', function() {})
// user.id.on('remove', function() {})
// user.id.on('change', function() {})
// user.id.off('update', function() {})
// user.id.off('empty', function() {})
// user.id.off('remove', function() {})
// user.id.off('change', function() {})
// user.id.trigger('update', function() {})
// user.id.trigger('empty', function() {})
// user.id.trigger('remove', function() {})
// user.id.trigger('change', function() {})
// user.id.empty()
// user.id.remove()

// user.valueOf()
// user.toJSON()
// user.toString()
// user.destroy()

